#ifndef __USARTPROTOCOL_H__
#define __USARTPROTOCOL_H__

#include "stm32l4xx_hal.h"
#include "var.h"
#include "assistfuncs.h"


#define BYTE_START 0xAF
#define BYTE_STOP 0xFA

enum IdRs232Cmd{
	NONE = 0,
	
	SET_VCO_CRS = 102,
	GET_VCO_CRS = 2,
	
	SET_VCO_FINE = 103,
	GET_VCO_FINE = 3,
	
	SET_COIL_CRNT = 104,
	GET_COIL_CRNT = 4,
	
	SET_VCSEL_DC = 105,
	GET_VCSEL_DC = 5,
	
	SET_RF_ATT = 106,
	GET_RF_ATT = 6,
	
	SET_AUX_TEC = 107,
	GET_AUX_TEC = 7,
	
	SET_REF_RES_VCSEL = 108,
	GET_REF_RES_VCSEL = 8,
	
	SET_REF_RES_AUX1 = 109,
	GET_REF_RES_AUX1 = 9,
	
	SET_REF_RES_CELL = 110,
	GET_REF_RES_CELL = 10,
	
	SET_REF_RES_AUX2 = 111,
	GET_REF_RES_AUX2 = 11,
	
	GET_TEMP_VCSEL = 12,
	GET_TEMP_AUX1 = 13,
	GET_TEMP_CELL = 14,
	GET_TEMP_AUX2 = 15,
	
	SET_LVL_TEMP_VCSEL = 116,
	GET_LVL_TEMP_VCSEL = 16,
	
	SET_LVL_TEMP_AUX1 = 117,
	GET_LVL_TEMP_AUX1 = 17,
	
	SET_LVL_TEMP_CELL = 118,
	GET_LVL_TEMP_CELL = 18,
	
	SET_LVL_TEMP_AUX2 = 119,
	GET_LVL_TEMP_AUX2 = 19,
	
	SET_TECCTRL_PID = 120,
	GET_TECCTRL_PID = 20,
	
	SET_DOPLER_CRNT_PID = 121,
	GET_DOPLER_CRNT_PID = 21,
	
	SET_VCO_PID = 122,
	GET_VCO_PID = 22,
	
	SET_CELLHTR_PID = 123,
	GET_CELLHTR_PID = 23,
	
	SET_AUXTEC_PID = 124,
	GET_AUXTEC_PID = 24,
	
	SET_DOPLER_TEMP_PID = 125,
	GET_DOPLER_TEMP_PID = 25,
	
	SET_OPTICS_PWR_PID = 126,
	GET_OPTICS_PWR_PID = 26,
	
	SET_RFATT_PID = 127,
	GET_RFATT_PID = 27,
	
	SET_TEC_CTRL = 128,
	GET_TEC_CTRL = 28,
	
	SET_CELL_HTR = 129,
	GET_CELL_HTR = 29,	
	
	SET_LOOP_PID = 130,
	GET_LOOP_PID = 30,

  SET_MODE_WORK = 131,
  GET_MODE_WORK = 31,

  SET_FREQ = 132,
  GET_FREQ = 32,
	
	SET_ITEM_TYPE_DETECTOR = 133,
	GET_ITEM_TYPE_DETECTOR = 33,
	
	SET_PHASE_TABLE_CRNT = 134,
	GET_PHASE_TABLE_CRNT = 34,
	
	SET_PHASE_TABLE_FREQ = 135,
	GET_PHASE_TABLE_FREQ = 35,
	
	SET_AMPLITUDE_MODULATION_FREQ = 136,
	GET_AMPLITUDE_MODULATION_FREQ = 36,
	
	SET_PHASE_MODULATION_FREQ = 137,
	GET_PHASE_MODULATION_FREQ = 37,
	
	SET_AMPLITUDE_MODULATION_CRNT = 138,
	GET_AMPLITUDE_MODULATION_CRNT = 38,
	
	SET_PHASE_MODULATION_CRNT = 139,
	GET_PHASE_MODULATION_CRNT = 39,
	
	SET_ITEM_SOURCE_DATA_CRNT = 140,
	GET_ITEM_SOURCE_DATA_CRNT = 40,
	
	SET_ITEM_SOURCE_DATA_FREQ = 141,
	GET_ITEM_SOURCE_DATA_FREQ = 41,
	
	SET_SHIFT_DETECTOR_FREQ = 142,
	GET_SHIFT_DETECTOR_FREQ = 42,
	
	SET_SHIFT_DETECTOR_DOPLER = 143,
	GET_SHIFT_DETECTOR_DOPLER = 43,
	
	SET_ITEM_TYPE_MOD_FREQ = 144,
	GET_ITEM_TYPE_MOD_FREQ = 44,
	
	SET_ITEM_TYPE_MOD_CRNT = 145,
	GET_ITEM_TYPE_MOD_CRNT = 45,
	
	SET_OPTION_VCSEL_DC = 146,
	GET_OPTION_VCSEL_DC = 46,
	
	SET_OPTION_POWER_RF_ATT = 147,
	GET_OPTION_POWER_RF_ATT = 47,
	
	SET_OPTION_AUX_TEC = 148,
	GET_OPTION_AUX_TEC = 48,
	
	SET_FREQ_WAVE = 149,
	GET_FREQ_WAVE = 49,
	
	SET_SHIFT_LMX_FREQ = 150,
	GET_SHIFT_LMX_FREQ = 50,
	
	GET_TEMP_BOARD = 51,
	
	SET_ACCESS_RS232 = 152,
	GET_ACCESS_RS232 = 52,
	
	SET_START_MODE = 153,
	GET_START_MODE = 53,

	SET_VCSEL_SCANLIMIT_MIN = 154,
	GET_VCSEL_SCANLIMIT_MIN = 54,
	
	SET_VCSEL_SCANLIMIT_MAX = 155,
	GET_VCSEL_SCANLIMIT_MAX = 55,

	SET_VCSEL_SCAN_STEP = 156,
	GET_VCSEL_SCAN_STEP = 56,
	
	SET_VCSEL_LVL_DETECTOR = 157,
	GET_VCSEL_LVL_DETECTOR = 57,
	
	SET_VCSEL_LVL_SIGMA = 158,
	GET_VCSEL_LVL_SIGMA = 58,
	
	SET_SCAN_FREQ_LIMIT_MIN = 159,
	GET_SCAN_FREQ_LIMIT_MIN = 59,
	
	SET_SCAN_FREQ_LIMIT_MAX = 160,
	GET_SCAN_FREQ_LIMIT_MAX = 60,
	
	SET_SCAN_FREQ_STEP = 161,
	GET_SCAN_FREQ_STEP = 61,
	
	SET_LVL_TEMP_CELL_RUN = 162,
	GET_LVL_TEMP_CELL_RUN = 62,
	
	GET_TEST_ID = 63,
	
	SET_OPTION_FIND_DC_PWR_RF = 164,
	GET_OPTION_FIND_DC_PWR_RF = 64,
	
	SET_OPTION_FACTOR_COIL = 165,
	GET_OPTION_FACTOR_COIL = 65,
	
	SET_FIX_VCSEL_DC = 166,
	GET_FIX_VCSEL_DC = 66,
	
	SET_MODCRNT_SHIFT = 167,
	GET_MODCRNT_SHIFT = 67,
	
	SET_OPTION_COIL_CRNT = 168,
	GET_OPTION_COIL_CRNT = 68,
	
	SET_OPTION_FACTOR_TEMP_FREQ = 169,
	GET_OPTION_FACTOR_TEMP_FREQ = 69,
	
	SET_OPTION_FACTOR_COIL_FREQ = 170,
	GET_OPTION_FACTOR_COIL_FREQ = 70,
	
	SET_OPTION_POLARITY_TEC = 171,
	GET_OPTION_POLARITY_TEC = 71,
	
	SET_SIGMA_VCSEL = 172,
	GET_SIGMA_VCSEL = 72,
	
  SET_SCAN_TEC_VCSEL_LIMIT_MIN = 173,
  GET_SCAN_TEC_VCSEL_LIMIT_MIN = 73,

  SET_SCAN_TEC_VCSEL_LIMIT_MAX = 174,
  GET_SCAN_TEC_VCSEL_LIMIT_MAX = 74,

  SET_SCAN_TEC_VCSEL_STEP = 175,
  GET_SCAN_TEC_VCSEL_STEP = 75,

  SET_ITEM_TABLE_COMPENSATION_FREQ = 176,
  GET_ITEM_TABLE_COMPENSATION_FREQ = 76,

  SET_USE_TABLE_COMPENSATION_FREQ = 177,
  GET_USE_TABLE_COMPENSATION_FREQ = 77,
	
	SET_PHASE_TABLE_RF = 178,
	GET_PHASE_TABLE_RF = 78,
	
	SET_ITEM_SOURCE_DATA_RF = 179,
	GET_ITEM_SOURCE_DATA_RF = 79,
	
	SET_SHIFT_VALUE_RF = 180,
	GET_SHIFT_VALUE_RF = 181,
	
	SAVE_OPTION_DATA = 200,
	LOAD_OPTION_DATA = 201,
	
	ADD_FREQ_WAVE = 202,
	
	STREAM_FREQ = 203,
	STREAM_SYS_TEMP = 204,
	SCREEN_DATA = 205,
	
	SET_FUSE_FLASH = 206,
	GET_FUSE_FLASH = 207,
	
	GET_ID_MC = 208,
	GET_VER_PROG = 209,
	GET_STATUS_CPT = 210,
	
	SET_UPDATE_STATUS_CPT = 211,
	GET_UPDATE_STATUS_CPT = 212,
	
	SET_OPTION_SLEEP = 213,
	GET_OPTION_SLEEP = 214,
	
	SET_SPEED_UART = 215,
	SET_IRQ_UART = 216,
	GET_IRQ_UART = 217,
	
	SET_CURRENT_PLL = 218,
	GET_CURRENT_PLL = 219,
	
	SET_COMP_CRNT_FUN = 220,
	GET_COMP_CRNT_FUN = 221,
	
	GET_MIN_MAX_SIZE_STEK_HEAP = 222,
	SET_SCOPE = 223,
	
	SET_PLL_N1 = 224,
	SET_PLL_N2 = 225,
	SET_PLL_N12 = 226,
	
  SET_DESIRED_CRNT = 227,
  GET_DESIRED_CRNT = 228,

  SET_PWR_ADJUSTMENT_PID = 229,
  GET_PWR_ADJUSTMENT_PID = 230,
	
	SET_AUTO_CAPTURE = 231,
	GET_AUTO_CAPTURE = 232,
	
	SET_HEAT_CAP = 233,
	GET_HEAT_CAP = 234,

	SET_MODDEMOD = 235,
  GET_MODDEMOD = 236
};

// Забираем байт из буфера
int USART_GetByte(void);
// Передаем байт в буфер
void USART_SendByte(uint8_t byte);
// Передаем строку в буфер
void USART_SendString(uint8_t* str, uint8_t count);
int GetCmdID(uint8_t* strCMD, uint16_t* countByte);
void CamputeCmd(int id);
void SendPkgData(int id, uint8_t* data, uint8_t countByte);
void SetOptionPID(int id, uint8_t* cmd, float* Kp, float* Ki, float* Kd);
void GetOptionPID(int id, float* Kp, float* Ki, float* Kd);
void GetTestValue(int id, uint32_t* a, uint32_t* b, uint32_t* c, uint32_t* d);

float unpackFloat(uint8_t *buf);
uint32_t packFloat(float value);
#endif


